<?php

// This is a sample configuration file, as the one that should be placed under scripts/
// Such a configuration file is automatically generated by the INSTALL script, but feel free to manually create one as per this model if necessary


// Server configuration
$db_server = 'localhost';
$db_name = 'my-db' ;
$db_user = 'root';
$db_password = 'mystr0nGp@55w0rd';

// Tables & email configuration
$site_admin = 'user@domain.com';
$mail_from = 'no-reply@domain.com';
$mail_replyto = 'support@domain.com';

// Site configuration
$indexURL = 'http://domain.com/index.php';
$siteName = 'My Site';

// DO NOT EDIT Create connection
try {
	$conn = new PDO("mysql:host=$db_server;dbname=$db_name;charset=utf8", $db_user, $db_password,
	array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
}
catch (Exception $e) {
	die('Erreur : ' . $e->getMessage());
}

?>